use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# FinancialSystemApiWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :financial_system_api, FinancialSystemApiWeb.Endpoint,
  load_from_system_env: true,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json",
  secret_key_base: System.get_env("SECRET_KEY") || "${SECRET_KEY}",
  server: true

# Configures Rancher
config :financial_system_api,
       :rancher_service_name,
       System.get_env("RANCHER_SERVICE_NAME") || "${RANCHER_SERVICE_NAME}"

# Configures Rancher Host IP
config :financial_system_api,
       :rancher_host_ip,
       System.get_env("RANCHER_HOST_IP") || "${RANCHER_HOST_IP}"

# Configures Rancher IP
config :financial_system_api,
       :rancher_ip,
       System.get_env("RANCHER_IP") || "${RANCHER_IP}"

# Configure your database
config :financial_system_api, FinancialSystemApi.Repo,
  database: System.get_env("DB_DATABASE") || "${DB_DATABASE}",
  ssl: true,
  pool_size: 3

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :financial_system_api, FinancialSystemApiWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :financial_system_api, FinancialSystemApiWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :financial_system_api, FinancialSystemApiWeb.Endpoint, server: true
#

# Configuring the prod enviroment
config :financial_system_api, :environment, :prod

# Configuring the prod statsd agent
config :financial_system_api, FinancialSystemApi.Statsd,
  statsd: DogStatsd,
  host: System.get_env("RANCHER_HOST_IP") || "${RANCHER_HOST_IP}",
  port: 8125
