sudo: required
services:
  - docker
  - postgresql
language: elixir
elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'
before_install:
  - chmod +x travis_merge_script.sh
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
script:
  - MIX_ENV=test mix build_travis
after_success:
  - ./travis_merge_script.sh
before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  skip_cleanup: true
  provider: script
  script: mix docker.shipit
  on:
    branch: master