dist: trusty
sudo: required
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
env:
  global:
    - PGPORT=5433
services:
  - docker
  - postgresql
language: elixir
elixir:
  - '1.6.0'
otp_release:
  - '20.2.2'
before_install:
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
  - chmod +x travis_merge_script.sh
  - chmod +x deploy.sh
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
script:
  - MIX_ENV=test mix build_travis
after_success:
  - ./travis_merge_script.sh
before_deploy:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
deploy:
  skip_cleanup: true
  provider: script
  script: bash deploy.sh
  on:
    branch: master